### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by skyeforeverblue** [Uhuh/RoleBot#50]
The bot's code is public, but what [free software](https://gnu.org/philosophy/free-sw.html) license is the source code being released under? [All code needs a license](https://blog.codinghorror.com/pick-a-license-any-license/), so this is very important. 

If you haven't decided on a license yet, here are a few suggestions:

- If you want to promote sharing and user freedom, the [GNU Affero General Public License, Version 3](https://www.gnu.org/licenses/agpl-3.0.en.html) is a good choice. It ensures that all RoleBot users have the freedom to run, copy, distribute, study, change and improve the bot. This is the best choice for freedom.
- If you *must* use a permissive license, use the [Apache License, version 2](https://www.apache.org/licenses/LICENSE-2.0), because it has user-protecting patent termination and indemnification provisions

Even though the permissive license is a "worse" choice than something copyleft like AGPL, any [GPL-compatible license](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses) is an acceptable choice.

**Comment by Uhuh** [comment]
When I made the project, I knew nothing about licenses. Truthfully, I'm still ignorant, but I'll put it under GPL3 like I did with my other project.

**Comment by skyeforeverblue** [comment]
It's important, because code without a license is by default "all rights reserved", meaning no one has *any* right to use, study, etc. the code at all. Thank you for choosing freedom!

**Comment by skyeforeverblue** [comment]
I should mention that the AGPL is specially suited for apps that run on servers. For normal software that you download and run as a desktop app on your PC, GPL is enough.
